controller:
  admin:
    username: "admin"
    password: "admin123"
  
  serviceAccount:
    create: false
    name: jenkins
  
  installPlugins:
    - git:latest
    - configuration-as-code:latest
    - kubernetes:latest
    - workflow-aggregator:latest
    - job-dsl:latest
    - kubernetes-cli:latest
  
  JCasC:
    configScripts:
      main-config: |
        jobs:
          - script: >
              pipelineJob('sample-app-pipeline') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/deividfsantos/deployment-system-poc')
                        }
                        branch('*/main')
                      }
                    }
                    scriptPath('app/sample-app/jenkinsfile')
                  }
                }
              }

rbac:
  create: true
  readSecrets: true

serviceAccount:
  create: true
  name: jenkins
