controller:
  image: "jenkins/jenkins"
  tag: "lts"
  
  adminUser: "admin"
  adminPassword: "admin123"
  
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  
  installPlugins:
    - kubernetes
    - kubernetes-cli
    - workflow-aggregator
    - git
    - configuration-as-code
    # - prometheus
    # - pipeline-stage-view
    - job-dsl
    # - pipeline-model-definition
    # - blueocean:latest
    # - docker-workflow:latest
    # - helm:latest
    # - kubernetes-cli:latest
    # - pipeline-utility-steps:latest
  
  JCasC:
    configScripts:
      main-config: |
        jenkins:
          systemMessage: "Deployment System Jenkins"
          numExecutors: 2
          securityRealm:
            local:
              allowsSignup: false
        jobs:
          - script: >
              pipelineJob('sample-app-pipeline') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/deividfsantos/deployment-system-poc')
                        }
                        branch('*/main')
                      }
                    }
                    scriptPath('app/sample-app/jenkinsfile')
                  }
                }
              }

  # prometheus:
  #   enabled: true
  #   serviceMonitorNamespace: "infrastructure"

persistence:
  enabled: true
  size: "5Gi"

rbac:
  create: true
  readSecrets: true

serviceAccount:
  create: true